config/routes.rb
Rails.application.routes.draw do

  root to: "items#index"
  devise_for :users

  resources :items do
    collection do
      get 'category_children'
      get 'category_grandchildren'
      get 'postage_children'
      get 'item_confilm'
      get 'search'
    end

    member do
      get 'goods_detail'
    end
  end


  resources :users do
    member do
      get 'goods'
      get 'purchase'
    end
  end


  resources :ragistrations do
    collection do
      get 'member'
      get 'authentication'
      get 'address'
      get 'complete'
      get 'userlogout'
      get 'payment'
    end
  end


  resources :cards, only: [:create, :show, :new, :index] do
    collection do
      post 'pay'
      post 'delete', to: 'cards#delete'
      post 'show'
      get 'confirmation'
      get 'mypay'
   

    end
  end


  resources :purchase, only: [:index] do
    member do
      get 'item_confilm', to: 'purchase#item_confilm'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items 
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :user, optional: true
 
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :items
  has_many :sizes, through: :size_categories
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :postage_day
  belongs_to_active_hash :state
  belongs_to :postage

  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  belongs_to :buyer,class_name:"User", optional: true
  belongs_to :user,class_name:"User", optional: true
  belongs_to :size, optional: true
  belongs_to :category, optional: true
  belongs_to :brand, optional: true


end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :item, optional: true
  mount_uploader :img, PhotoUploader
  

end

app/models/postage.rb
class Postage < ApplicationRecord
  has_ancestry
  has_many :items
end

app/models/postage_day.rb
class PostageDay < ActiveHash::Base
  self.data = [ 
                {id: 1, postage_day: '1~2日で発送'},
                {id: 2, postage_day: '2~3日で発送'},
                {id: 3, postage_day: '4~7日で発送'}
  ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
                {id: 1, prefecture: '北海道'}, {id: 2, prefecture: '青森県'}, {id: 3, prefecture: '岩手県'},
                {id: 4, prefecture: '宮城県'}, {id: 5, prefecture: '秋田県'}, {id: 6, prefecture: '山形県'},
                {id: 7, prefecture: '福島県'}, {id: 8, prefecture: '茨城県'}, {id: 9, prefecture: '栃木県'},
                {id: 10, prefecture: '群馬県'}, {id: 11, prefecture: '埼玉県'}, {id: 12, prefecture: '千葉県'},
                {id: 13, prefecture: '東京都'}, {id: 14, prefecture: '神奈川県'}, {id: 15, prefecture: '新潟県'},
                {id: 16, prefecture: '富山県'}, {id: 17, prefecture: '石川県'}, {id: 18, prefecture: '福井県'},
                {id: 19, prefecture: '山梨県'}, {id: 20, prefecture: '長野県'}, {id: 21, prefecture: '岐阜県'},
                {id: 22, prefecture: '静岡県'}, {id: 23, prefecture: '愛知県'}, {id: 24, prefecture: '三重県'},
                {id: 25, prefecture: '滋賀県'}, {id: 26, prefecture: '京都府'}, {id: 27, prefecture: '大阪府'},
                {id: 28, prefecture: '兵庫県'}, {id: 29, prefecture: '奈良県'}, {id: 30, prefecture: '和歌山県'},
                {id: 31, prefecture: '鳥取県'}, {id: 32, prefecture: '島根県'}, {id: 33, prefecture: '岡山県'},
                {id: 34, prefecture: '広島県'}, {id: 35, prefecture: '山口県'}, {id: 36, prefecture: '徳島県'},
                {id: 37, prefecture: '香川県'}, {id: 38, prefecture: '愛媛県'}, {id: 39, prefecture: '高知県'},
                {id: 40, prefecture: '福岡県'}, {id: 41, prefecture: '佐賀県'}, {id: 42, prefecture: '長崎県'},
                {id: 43, prefecture: '熊本県'}, {id: 44, prefecture: '大分県'}, {id: 45, prefecture: '宮崎県'},
                {id: 46, prefecture: '鹿児島県'}, {id: 47, prefecture: '沖縄県'}, {id:48, prefecture: '未定'}

  ]

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
  has_many :categories, through: :size_categories
end

app/models/size_category.rb
class SizeCategory < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :size, optional: true
end

app/models/state.rb
class State < ActiveHash::Base
  self.data = [
                {id: 1, state: "新品､未使用"}, {id: 2, state: "未使用に近い"}, {id: 3, state: "目立った傷や汚れあり"}, 
                {id: 4, state: "やや傷や汚れあり"}, {id: 5, state: "傷や汚れあり"}, {id: 6, state: "全体的に状態が悪い"}
  ]
end

app/models/street.rb
class Street < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :items
         
         has_one :card
         has_one :profile
         has_one :street


         accepts_nested_attributes_for :street

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.find_by(id: current_user)
  end

  def show
    user = User.find(params[:id])
    @prefecrure = Prefecture.all
    @search_params = User.find(params[:id])
    @street = current_user.street
  end


  def update
  end

  def edit
    @user = User.find(params[:id])
  end

  def purchase
    @items = Item.where(user: current_user)
    @sold = Item.where( buyer_id: current_user.id)
    @photos = Photo.where(params[:use_id])
  end


  def goods
    @items = Item.where(user: current_user)
  end

  private

  def user_search_params
    params.fetch(:search, {}).permit(:id,:prefecture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/payjp_helper.rb
module PayjpHelper
  def embedded_svg filename, options={}
    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
end

class MyPayjp
  Payjp::api_key = ENV['PAYJP_PRIVATE_KEY']
end
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
= render 'shared/header'
- breadcrumb :edit_user
= render 'shared/breadcrumbs'
.main-box
  .mypage-main
    = render 'shared/side-bar'
    .right-container
      .projects
        %h2.topic
          プロフィール
        = form_with url: users_path, id: "topic-form" do |f|
          .nickname-edit
            = image_tag 'mer.png', alt: '', height: '60', width: '60', id: 'img-top'
            = f.text_field :name, class: "nickname", value: "#{@user.nickname}"
          .about-edit
            = f.text_area :content, class: "p-about", placeholder: "例）こんにちは☆ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に９号です。気持ちよく取引できるようできるよう心がけていますので、商品や発送方法などなどご質問がありましたらお気軽にどうぞ♪"
            = f.submit "変更", class: "p-edit"

= render 'shared/footer'
= render 'shared/exhibition-btn'

app/views/users/goods.html.haml
.wrapper
  = render 'shared/header'
  - breadcrumb :goods_user
  = render 'shared/breadcrumbs'
  .main-box
    .mypage-main
      = render 'shared/side-bar'
      .right-container
        .goods-box-title
          出品した商品
        .goods-box-example
          .example-1
            出品中
          .example-2
            取引中
          .example-3
            売却済み
        %ul
          - @items.each do |item|
            %li
              = link_to goods_detail_item_path(item), class: "goods-main-c" do
                .goods-list-box
                  .goods-photo
                    = image_tag item.photos[0].img.url, size: '60x60'
                    -if item.buyer_id.present?
                      .items-box_photo__sold
                        .items-box_photo__sold__inner
                          SOLD
                  .goods-name
                    .name-fine
                      = item.name
                    .goods-price
                      = item.price
                      円
                    .goods-icon-list
                      =fa_icon 'heart-o', class: 'heart-item'
                      %span &nbsp;0&nbsp;
                      =fa_icon 'comment-o', class: 'comment-item'
                      %span &nbsp;0&nbsp;&nbsp;
                      .font-goods
                        出品中
                    =fa_icon 'angle-right 2x', class: 'angle-item', height: '100', width: '100'


  = render 'shared/footer'
  = render 'shared/exhibition-btn'

app/views/users/goods_detail.html.haml
.wrapper
  = render 'shared/header'
  - breadcrumb :goods_detail
  = render 'shared/breadcrumbs'

  .detail-main-box
    -# 後でrenderする商品の詳細ページview
    .action-choice-content
      .action-edit-c
        %a.choice-goods-edit{href: "/items"}商品の編集
      %p.text-or
        or
      .destroy-content
        = link_to 'この商品を削除する', item_path(@item), method: :delete, class: "choice-destroy", data: {confirm: "本当に削除しますか？"}


  = render 'shared/footer'
  = render 'shared/exhibition-btn'

app/views/users/index.html.haml
.wrapper
  = render 'shared/header'
  - breadcrumb :index_user
  = render 'shared/breadcrumbs'
  .main-box
    .mypage-main
      = render 'shared/side-bar'
      .right-container
        .user-top
          %a.top-box
            .user-img
              = image_tag 'mer.png', alt: '', height: '60', width: '60', id: 'img-top'
            .user-nick
              = @user.nickname
            .user-val
              評価
              %span.bold 0
              出品数
              %span.bold 0
        .user-notice
          %ul.user-tab
            %li.active-1
              %h3
                %a.do-1
                  お知らせ
            %li.active-2
              %h3
                %a.do-2
                  やることリスト
          .user-box
            = image_tag 'mer-i', alt: '', height: '100', width: '120', id: 'box-img'
            %ul.list-box
              %li.not-find-box-1
                現在、お知らせはありません

  = render 'shared/footer'
  = render 'shared/exhibition-btn'

app/views/users/purchase.haml
.wrapper
  = render 'shared/header'
  - breadcrumb :purchase_user
  = render 'shared/breadcrumbs'
  .main-box
    .mypage-main
      = render 'shared/side-bar'
      .right-container
        .goods-box-title
          購入した商品
        .goods-box-example
          .example-1
            取引中
          .example-2
            過去の取引
        %ul
          - @sold.each do |item|
            %li
              = link_to goods_detail_item_path(item), class: "goods-main-c" do
                .goods-list-box
                  .goods-photo
                    = image_tag item.photos[0].img.url, size: '60x60'
                  .goods-name
                    .name-fine
                      = item.name
                    .goods-price
                      = item.price
                      円
                    .goods-icon-list
                      =fa_icon 'heart-o', class: 'heart-item'
                      %span &nbsp;0&nbsp;
                      =fa_icon 'comment-o', class: 'comment-item'
                      %span &nbsp;0&nbsp;&nbsp;
                      .font-goods
                        取引中
                    =fa_icon 'angle-right 2x', class: 'angle-item', height: '100', width: '100'


  = render 'shared/footer'
  = render 'shared/exhibition-btn'

app/views/users/show.haml
= render 'shared/header'
= render 'shared/user-right'
= render 'shared/footer'

app/views/users/show.html.haml
.wrapper
  = render 'shared/header'
  - breadcrumb :show_user
  = render 'shared/breadcrumbs'
  .main-box
    .mypage-main
      = render 'shared/side-bar'
      .right-container
        .user-top
          %a.top-box
            .user-img
              = image_tag 'mer.png', alt: '', height: '60', width: '60', id: 'img-top'
            .user-nick
              りょう
            .user-val
              評価
              %span.bold 0
              出品数
              %span.bold 0
        .user-notice
          %ul.user-tab
            %li.active-1
              %h3
                %a.do-1
                  お知らせ
            %li.active-2
              %h3
                %a.do-2
                  やることリスト
          .user-box
            = image_tag 'mer-i', alt: '', height: '100', width: '120', id: 'box-img'
            %ul.list-box
              %li.not-find-box-1
                現在、お知らせはありません
            -# %ul
            -#   %li.not-find-box-2
            -#     現在、やることリストはありません
        .user-history
          %h2.history-head
            購入した商品
          %ul.history-tab
            %li.active-3
              %a.do-3
                取引中
            %li.active-4
              %a.do-4
                過去の取引
          .history-box
            = image_tag 'mer-i.png', alt: '', height: '100', width: '120', id: 'box-img'
            %ul.history-list
              %li.not-find-history-1
                取引中の商品がありません
              -# %li.not-find-history-2
              -#   過去に取引した商品がありません

  = render 'shared/footer'
  = render 'shared/exhibition-btn'