config/routes.rb
Rails.application.routes.draw do

  root to: "items#index"
  devise_for :users

  resources :items do
    collection do
      get 'category_children'
      get 'category_grandchildren'
      get 'postage_children'
      get 'item_confilm'
      get 'search'
    end

    member do
      get 'goods_detail'
    end
  end


  resources :users do
    member do
      get 'goods'
      get 'purchase'
    end
  end


  resources :ragistrations do
    collection do
      get 'member'
      get 'authentication'
      get 'address'
      get 'complete'
      get 'userlogout'
      get 'payment'
    end
  end


  resources :cards, only: [:create, :show, :new, :index] do
    collection do
      post 'pay'
      post 'delete', to: 'cards#delete'
      post 'show'
      get 'confirmation'
      get 'mypay'
   

    end
  end


  resources :purchase, only: [:index] do
    member do
      get 'item_confilm', to: 'purchase#item_confilm'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items 
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :user, optional: true
 
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :items
  has_many :sizes, through: :size_categories
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :postage_day
  belongs_to_active_hash :state
  belongs_to :postage

  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  belongs_to :buyer,class_name:"User", optional: true
  belongs_to :user,class_name:"User", optional: true
  belongs_to :size, optional: true
  belongs_to :category, optional: true
  belongs_to :brand, optional: true


end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :item, optional: true
  mount_uploader :img, PhotoUploader
  

end

app/models/postage.rb
class Postage < ApplicationRecord
  has_ancestry
  has_many :items
end

app/models/postage_day.rb
class PostageDay < ActiveHash::Base
  self.data = [ 
                {id: 1, postage_day: '1~2日で発送'},
                {id: 2, postage_day: '2~3日で発送'},
                {id: 3, postage_day: '4~7日で発送'}
  ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
                {id: 1, prefecture: '北海道'}, {id: 2, prefecture: '青森県'}, {id: 3, prefecture: '岩手県'},
                {id: 4, prefecture: '宮城県'}, {id: 5, prefecture: '秋田県'}, {id: 6, prefecture: '山形県'},
                {id: 7, prefecture: '福島県'}, {id: 8, prefecture: '茨城県'}, {id: 9, prefecture: '栃木県'},
                {id: 10, prefecture: '群馬県'}, {id: 11, prefecture: '埼玉県'}, {id: 12, prefecture: '千葉県'},
                {id: 13, prefecture: '東京都'}, {id: 14, prefecture: '神奈川県'}, {id: 15, prefecture: '新潟県'},
                {id: 16, prefecture: '富山県'}, {id: 17, prefecture: '石川県'}, {id: 18, prefecture: '福井県'},
                {id: 19, prefecture: '山梨県'}, {id: 20, prefecture: '長野県'}, {id: 21, prefecture: '岐阜県'},
                {id: 22, prefecture: '静岡県'}, {id: 23, prefecture: '愛知県'}, {id: 24, prefecture: '三重県'},
                {id: 25, prefecture: '滋賀県'}, {id: 26, prefecture: '京都府'}, {id: 27, prefecture: '大阪府'},
                {id: 28, prefecture: '兵庫県'}, {id: 29, prefecture: '奈良県'}, {id: 30, prefecture: '和歌山県'},
                {id: 31, prefecture: '鳥取県'}, {id: 32, prefecture: '島根県'}, {id: 33, prefecture: '岡山県'},
                {id: 34, prefecture: '広島県'}, {id: 35, prefecture: '山口県'}, {id: 36, prefecture: '徳島県'},
                {id: 37, prefecture: '香川県'}, {id: 38, prefecture: '愛媛県'}, {id: 39, prefecture: '高知県'},
                {id: 40, prefecture: '福岡県'}, {id: 41, prefecture: '佐賀県'}, {id: 42, prefecture: '長崎県'},
                {id: 43, prefecture: '熊本県'}, {id: 44, prefecture: '大分県'}, {id: 45, prefecture: '宮崎県'},
                {id: 46, prefecture: '鹿児島県'}, {id: 47, prefecture: '沖縄県'}, {id:48, prefecture: '未定'}

  ]

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
  has_many :categories, through: :size_categories
end

app/models/size_category.rb
class SizeCategory < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :size, optional: true
end

app/models/state.rb
class State < ActiveHash::Base
  self.data = [
                {id: 1, state: "新品､未使用"}, {id: 2, state: "未使用に近い"}, {id: 3, state: "目立った傷や汚れあり"}, 
                {id: 4, state: "やや傷や汚れあり"}, {id: 5, state: "傷や汚れあり"}, {id: 6, state: "全体的に状態が悪い"}
  ]
end

app/models/street.rb
class Street < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :items
         
         has_one :card
         has_one :profile
         has_one :street


         accepts_nested_attributes_for :street

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/payjp_helper.rb
module PayjpHelper
  def embedded_svg filename, options={}
    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
end

class MyPayjp
  Payjp::api_key = ENV['PAYJP_PRIVATE_KEY']
end
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_all-items.haml
= link_to item_path(item.id), class:"itmes-main-link" do
  .product
    .photo-zone
      = image_tag item.photos[0].img.url , width: "100%", height: "100%"
      -if item.buyer_id.present?
        .items-box_photo__sold
          .items-box_photo__sold__inner
            SOLD
    .data
      .name
        = item.name
      .price
        ¥
        = item.price

app/views/shared/_breadcrumbs.html.haml
.bread
  = breadcrumbs separator: " &rsaquo; "

app/views/shared/_exhibition-btn.haml
-# 出品ボタン
- if user_signed_in?
  = link_to new_item_path do
    .exhibition-btn
      .exhibition-btn__text
        出品
      .exhibition-btn__icon
        =fa_icon 'camera', class: "camera-icon"
- else
  = link_to new_user_session_path do
    .exhibition-btn
      .exhibition-btn__text
        出品
      .exhibition-btn__icon
        =fa_icon 'camera', class: "camera-icon"


-# = link_to new_item_path do
-#   .exhibition-btn
-#     .exhibition-btn__text
-#       出品
-#     .exhibition-btn__icon
-#       =fa_icon 'camera', class: "camera-icon"

app/views/shared/_header.haml
.header
  .inner
    .top
      .title
        = link_to root_path do
          %img{src: "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?863303983",width:'134px',height:'36px'}
      .form
        = form_with url: search_items_path, method: :get, local: true do |f|
          = f.text_field :keyword, class: 'form__search', placeholder: '何をお探しで？',name: 'keyword',type:'search'
          %label.search-label{for: "search-icon"}
            %i.fa.fa-search
            = f.submit '', id: "search-icon"

    .under
      %nav.left
        %ul.header-navi
          %li.header-l-left
            = fa_icon 'list-ul', class: 'category-icon'
            %span カテゴリーから探す
          %li.header-l-right
            = fa_icon 'tag',class: 'brand-icon'
            %span ブランドから探す
      .right
        - if user_signed_in?
          .header-like-box
            .like-icon-box
              = fa_icon 'heart-o' ,class:'like-header'
            .like-text-box
              いいね!一覧
          .header-notice
            .notice-icon-box
              = fa_icon 'bell-o' , class: 'bell-header'
            .notice-text-box
              お知らせ
          .header-to-do-list
            .check-icon-box
              = fa_icon 'check' , class: 'check-header'
            .check-text-box
              やることリスト
          .header-mypage-box
            .header-mypage-url
              = link_to "マイページ",  users_path , class: 'mypage-kondou'
        - else
          .new-create-user
            = link_to "新規会員登録", new_user_registration_path, class: 'new-ragistration-text'
          .login-user-box
            = link_to "ログイン" , new_user_session_path, class: 'new-user-text'

app/views/shared/_product-details.haml
.wrapper
  .all-contents
    .all-contents__prduct-details-1
      .product-details-2
        .product-details-3
          = @items.name
        .product-description
        .product-details-4
          .product-details-5
            .photo-box-1
              = image_tag @items.photos[0].img.url, width: "100%", height: "100%"
            .photo-box-2
              - @items.photos.each do |image|
                .mini-photo
                  = image_tag image.img.url , width: "100%", height: "100%"
          .product-details-6
            .product-details-7
              .left-text-1
                出品者
              .right-zone-1
                .right-zone-1-1
                  = @items.user.nickname
                .right-zone-1-2
                  .evaluation-icon
                    = fa_icon 'twitter', class: "good-icon"
                  .evaluation-num
                    56
                  .evaluation-icon
                    = fa_icon 'twitter', class: "normal-icon"
                  .evaluation-num
                    34
                  .evaluation-icon
                    = fa_icon 'twitter', class: "bad-icon"
                  .evaluation-num
                    12
            .product-details-8
              .left-text-2
                カテゴリー
              .right-zone-2
                .right-zone-2-1
                  .right-zone-2-2
                    = @items.category.root.category_name
                  .right-zone-2-3
                    >
                    = @items.category.parent.category_name
                  .right-zone-2-4
                    >
                    = @items.category.category_name
            -# .product-details-9
            -#   .left-text-3
            -#     ブランド
            -#   .right-zone-3
            -#     .right-zone-3-1
            -#       ーーー
            .product-details-9
              .left-text-3
                商品の状態
              .right-zone-3
                .right-zone-3-1b
                  = @items.state.state
            .product-details-9
              .left-text-3
                配送料の負担
              .right-zone-3
                .right-zone-3-1b
                  = @items.postage.root.postage
            .product-details-9
              .left-text-3
                配送の方法
              .right-zone-3
                .right-zone-3-1b
                  = @items.postage.postage
            .product-details-9
              .left-text-3
                配送元地域
              .right-zone-3
                .right-zone-3-1
                  = @items.prefecture.prefecture
            .product-details-9
              .left-text-3
                発送日の目安
              .right-zone-3
                .right-zone-3-1b
                  = @items.postage_day.postage_day

        .product-details-15
          .product-details-16
            .product-details-17
              ¥
              = @items.price
            .product-details-18
              （税込）
            .product-details-19
              送料込み

        -if @items.user_id == current_user.id || @items.buyer_id.present?
        -else
          .product-details-20
            .product-details-21
              = link_to "購入画面に進む", item_confilm_purchase_path(@items) ,calss:"item-confilm"

        .product-details-22
          = @items.explain
        .product-details-23

          .product-details-24
            .product-details-30
              .product-details-31
                = fa_icon 'twitter', class: "iine-icon"
              .product-details-26
                いいね！
              .product-details-35
                77

            .product-details-32
              .product-details-33
                = fa_icon 'twitter', class: "flag-icon"
              .product-details-27
                不適切な商品の報告

          .product-details-28
            .product-details-34
              = fa_icon 'twitter', class: "key-icon"
            .product-details-29
              あんしん・あんぜんへの取り組み

      .product-details-36
        .product-details-37
          < ザ・ベスト・コレクション
        .product-details-38
          iPhone 純正 コンセント >

      .details-comment-box
        .details-in-box
          .details-text-box
            相手のことを考え丁寧なコメントを心掛けましょう。不快な言葉遣いなどは利用制限や退会処分とな
            %br/
            ることがあります。
          = form_with do |c|
            .details-comment-form
              = c.text_area :p , class: 'coment-text-area'
            .details-comment-submit
              = c.submit :"コメント" , class: 'coment-submit-b'

      .comment-under-box
        .before-box
          < 時計
        .after-box
          パジャマ >

      .details-icon-box
        %ul.details-icon-main
          %li.details-facebook
            = fa_icon 'facebook-square', class: 'd-facebook'
          %li.details-twitter
            = fa_icon 'twitter-square' , class: 'd-twitter'
          %li.details-line
            = fa_icon 'vine' ,class: 'd-vine'
          %li.details-pinster
            = fa_icon 'pinterest' , class: 'd-pint'

app/views/shared/_side-bar.haml
.side-bar
  %nav.bar
    .mypage
      %li
        = link_to "マイページ",  users_path, class:'log-out-text'
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        お知らせ
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        やることリスト
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        いいね！一覧
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        = link_to new_item_path, style: "color: #333;" do
          出品する
          = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        = link_to "出品した商品 - 出品中", goods_user_path(current_user), class:'log-out-text'
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        出品した商品 - 取引中
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        出品した商品 - 売却済み
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        =link_to "購入した商品 - 取引中", purchase_user_path(current_user),class:'log-out-text'
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        購入した商品 - 過去の取引
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        ニュース一覧
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        評価一覧
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        ガイド
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        お知らせ
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 

    .merpay
      %h3
        メルぺイ
      %li
        売上・振込申請
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        ポイント
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 

    .config
      %h3
        設定
      %li
        = link_to "プロフィール", edit_user_path(current_user), class:'log-out-text'
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        発送元・お届け先住所変更
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        = link_to "支払先方法", mypay_cards_path, class:'payment-text'
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        メール/パスワード
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        = link_to "本人情報", user_path(current_user), class:'log-out-text'
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        電話番号
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 
      %li
        = link_to "ログアウト", userlogout_ragistrations_path, class:'log-out-text'
        = fa_icon 'chevron-right', class: 'icon-arrow-right' 

app/views/shared/_under-banner.haml
-# フッターの上のバナー部分
.under-banner
  = image_tag 'under-banner.png', class: "under-banner-img"

app/views/user-shared/_address-center.haml
.address-box
  .address-center-box
    .__address-small-text
      住所入力
    .__address-small-box
      .__address-list-box
        = form_with model: @user,  url: ragistrations_path , method: :post, local: true do |f|
          .__l-address-form
            .__l-a-text
              = f.label :"お名前"
            .__l-a-required
              必須
          .__onamae-box
            .__onamae-myouzi 
            = f.text_field :first_name, placeholder: "例)山田", class: "text-address"
            .__onamae-namae
            = f.text_field :last_name, placeholder: "例)彩", class: "text-address"

          .__l-address-form
            .__l-a-text
              = f.label :"お名前カナ"
            .__l-a-required
              必須
          .__onamae-kana-box
            .__onamae-kana-myouzi
            = f.text_field :first_kana, placeholder: "例)ヤマダ", class: "text-address"
            .__onamae-kana-namae
            = f.text_field :last_kana, placeholder: "例)アヤ", class: "text-address"

          = f.fields_for :street do |p|
            .__l-address-form
              .__l-a-text
                = p.label :"郵便番号"
              .__l-a-required
                必須
            = p.text_field :post, placeholder: " 例) 123-4567", class: "text-address"

            .__l-address-form
              .__l-a-text
                = p.label :"都道府県"
              .__l-a-required
                必須
            = p.collection_select(:prefecture, Prefecture.all ,:prefecture, :prefecture, prompt: "--")
            .__l-address-form
              .__l-a-text
                = p.label :"市区町村"
              .__l-a-required
                必須
            = p.text_field :city, placeholder: "例) 横浜市緑区", class: "text-address"

            .__l-address-form
              .__l-a-text
                = p.label :"番地"
              .__l-a-required
                必須
            = p.text_field :address, placeholder: "例) 青山1-1-1", class: "text-address"

            .__l-address-form
              .__l-a-text
                = p.label :"建物名"
              .__a-l-required
                任意
            = p.text_field :bilding, placeholder: "例) 柳ビル103", class: "text-address"

            .__l-address-form
              .__l-a-text
                = p.label :"電話"
              .__a-l-required
                任意
            = p.telephone_field :phone, placeholder: "例) 09012345678", class: "text-address"

            .__address-red-move
              = f.submit "次へ進む" , class: "address-payment"

app/views/user-shared/_complete-center.haml
.complete-box
  .complete-center-box
    .__complete-small-text
      会員登録完了
    .__complete-small-box
      .__complete-list-box
        = form_with model: @user , url: items_path , method: :get , local: true do |f|
          .__complete-big-textbox
            ありがとうございます。
            %br/
            会員登録が完了しました。
          .__complete-red-move
            = f.submit "メルカリを始める" , class: "coplete-move"

app/views/user-shared/_info-authentication.haml
.authentication-box
  .authentication-small-box
    .__call-number-text
      電話番号認証
    .call-center
      = form_with model: @user , url: address_ragistrations_path, method: :get , local: true do |f|
        .__list-call-form
          .__list-call-number-text
            = f.label :"携帯電話の番号"
          .__list-call-field
            = f.telephone_field :call_number, placeholder: "携帯電話の番号を入力", class: "text-call"
          .__list-short-text
            本人確認のため、携帯電話のSMS(ショートメッセージ
            %br/
            サービス)を利用して認証します。
          .__l-call-text
            = f.submit "SMSを送信する", class: "sms-text-box"

          .list-call-under-text
            ※電話番号は本人確認や不正利用帽子のために利用し
            %br/
            ます。他のユーザーに公開されることはありません。
          .list-call-authen
            電話番号の確認が必要な理由>

app/views/user-shared/_info-center.haml
.info-center-box
  .center-info-main
    .__info-small-text
      会員情報登録
    .__info-center-small
      .__info-list
        = form_with model: @user, url: authentication_ragistrations_path , method: :get , local: true do |f|
          .__list-from
            .__info-form-text
              = f.label :"ニックネーム"
            .__list-required
              必須
          = f.text_field :nickname, placeholder: "例)メルカリ太郎", class: "text-info"
          -# パスワード
          .__list-from
            .__info-form-text
              = f.label :"メールアドレス"
            .__list-required
              必須
          = f.email_field :email, placeholder: "メールアドレス", class: "text-info"
          .__list-from
            .__info-form-text
              = f.label :"パスワード"
            .__list-required
              必須
          = f.password_field :password, placeholder: "8文字以上", class: "text-info"
          .__list-from
            .__info-form-text
              = f.label :"パスワード(確認)"
            .__list-required
              必須
          = f.password_field :password_confirmation, placeholder: "8文字以上", class: "text-info"

          -# 本人確認テキスト
          .__list-from
            本人確認
          %br
            .list-text-box
              安心・安全にご利用していただくために、お客さまの本人
              %br/
              情報の登録にご協力ください。他のお客さまに公開さ
              %br/
              れることはありません。

          -# 名前全角
          .__list-from
            .__info-form-text
              = f.label :"お名前(全角)"
            .__list-required
              必須
          .__zenkaku-box
            .__zenkaku-name-1
            = f.text_field :first_name, placeholder: "例)山田", class: "text-info"
            .__zenkaku-name-2
            = f.text_field :last_name, placeholder: "例彩", class: "text-info"

          -# 名前カタカナ
          .__list-from
            .__info-form-text
              = f.label :"お名前カナ(全角)"
            .__list-required
              必須
          .__katakana-box
            .__katakana-name-1
            = f.text_field :first_kana, placeholder: "例)ヤマダ", class: "text-info"
            .__katakana-name-2
            = f.text_field :last_kana, placeholder: "例)アヤ", class: "text-info"

          -# 生年月日フォーム
          .__list-from
            .__info-form-text
              = f.label :"生年月日"
            .__list-required
              必須

          -# 生年月日フォーム
          .__info-pull-box
            .__info-pull-mouth
            = raw sprintf( f.date_select(:birth_day , use_month_numbers: true , start_year: 1930 , end_year: (Time.now.year + 5) , default: Date.new(1989, 1, 1),date_separator: '%s'),'年 ', '月 ') + '日'

          -# 本人情報テキスト
          .__list-render-text
            ※本人情報は正しく入力してください。会員登録後、
            %br/
            修正するにはお時間を頂く場合があります。

          .__center-under-info
            .__info-under-small
              .l-form-checker
                .__l-mini-box
                  .__l-small-checker
                    = check_box :check_box, class: 'small-check'
                  .__l-text
                    私はロボットではあり
                    %br
                    ません
                  .__l-icon
                    = fa_icon 'internet-explorer', class: 'll-icon'
                  .__l-under-text
                    プライバシー・利用規約

              .text-up-box
                .text-sevice-box
                  「次へ進む」のボタンを押すことによ利用規約に
              .text-consent-box
                同意したものとみなします

              .red-move-on-btn
                = f.submit "次へ進む", class: "move-on-red"
              .move-on-under-text
                本人情報の登録について

app/views/user-shared/_payment.haml
.payment-box
  .payment-center-box
    .__payment-small-text
      支払い方法
    .__payment-small-box
      .__payment-list-box
        = form_with model: @user , url: complete_ragistrations_path, method: :get, local: true do |pay|
          .__l-payment-form
            .__l-p-text
              = pay.label :"カード番号"
            .__l-p-required
              必須
          = pay.text_field :card_naumber, placeholder: "半角数字のみ", class: "text-payment"

          .__l-payment-form
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?917505326", width:  "49"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?917505326", width:  "34"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?917505326", width:  "30"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?917505326", width:  "32"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?917505326", width:  "21"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?917505326", width:  "32"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?917505326", width:  "32"}


          .__l-payment-form
            .__l-p-text
              = pay.label :"有効期限"
            .__l-p-required
              必須
          .__payment-pull-box
            .__payment-pull-mouth
            = render "user-shared/pull-down-birthday/pull-mouth"
            .__payment-pull-text
              月
            .__payment-pull-day
            = render "user-shared/pull-down-birthday/pull-short-year"
            .__payment-pull-text
              年

          .__l-payment-form
            .__l-p-text
              = pay.label :"セキュリティーコード"
            .__l-p-required
              必須
          = pay.text_field :security_code, placeholder: " カード背面4桁もしくは3桁の番号", class: "text-payment"

          .__payment-under-text
            カード裏面の番号とは？

          .__payment-move-on-btn
            = pay.submit "次へ進む", class: "payment-move-text"

app/views/user-shared/_paymnet.haml
.payment-box
  .payment-center-box
    .__payment-small-text
      支払い方法
    .__payment-small-box
      .__payment-list-box
        = form_with model: @user , url: complete_ragistrations_path, method: :get, local: true do |pay|
          .__l-payment-form
            .__l-p-text
              = pay.label :"カード番号"
            .__l-p-required
              必須
          = pay.text_field :card_naumber, placeholder: "半角数字のみ", class: "text-payment"

          .__l-payment-form
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?917505326", width:  "49"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?917505326", width:  "34"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?917505326", width:  "30"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?917505326", width:  "32"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?917505326", width:  "21"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?917505326", width:  "32"}
          %img{alt:  "", height:  "20", src:  "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?917505326", width:  "32"}


          .__l-payment-form
            .__l-p-text
              = pay.label :"有効期限"
            .__l-p-required
              必須
          .__payment-pull-box
            .__payment-pull-mouth
            = render "user-shared/pull-down-birthday/pull-mouth"
            .__payment-pull-text
              月
            .__payment-pull-day
            = render "user-shared/pull-down-birthday/pull-short-year"
            .__payment-pull-text
              年

          .__l-payment-form
            .__l-p-text
              = pay.label :"セキュリティーコード"
            .__l-p-required
              必須
          = pay.text_field :security_code, placeholder: " カード背面4桁もしくは3桁の番号", class: "text-payment"

          .__payment-under-text
            カード裏面の番号とは？

          .__payment-move-on-btn
            = pay.submit "次へ進む", class: "payment-move-text"