config/routes.rb
Rails.application.routes.draw do

  root to: "items#index"
  devise_for :users

  resources :items do
    collection do
      get 'category_children'
      get 'category_grandchildren'
      get 'postage_children'
      get 'item_confilm'
      get 'search'
    end

    member do
      get 'goods_detail'
    end
  end


  resources :users do
    member do
      get 'goods'
      get 'purchase'
    end
  end


  resources :ragistrations do
    collection do
      get 'member'
      get 'authentication'
      get 'address'
      get 'complete'
      get 'userlogout'
      get 'payment'
    end
  end


  resources :cards, only: [:create, :show, :new, :index] do
    collection do
      post 'pay'
      post 'delete', to: 'cards#delete'
      post 'show'
      get 'confirmation'
      get 'mypay'
   

    end
  end


  resources :purchase, only: [:index] do
    member do
      get 'item_confilm', to: 'purchase#item_confilm'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items 
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :user, optional: true
 
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :items
  has_many :sizes, through: :size_categories
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :postage_day
  belongs_to_active_hash :state
  belongs_to :postage

  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  belongs_to :buyer,class_name:"User", optional: true
  belongs_to :user,class_name:"User", optional: true
  belongs_to :size, optional: true
  belongs_to :category, optional: true
  belongs_to :brand, optional: true


end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :item, optional: true
  mount_uploader :img, PhotoUploader
  

end

app/models/postage.rb
class Postage < ApplicationRecord
  has_ancestry
  has_many :items
end

app/models/postage_day.rb
class PostageDay < ActiveHash::Base
  self.data = [ 
                {id: 1, postage_day: '1~2日で発送'},
                {id: 2, postage_day: '2~3日で発送'},
                {id: 3, postage_day: '4~7日で発送'}
  ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
                {id: 1, prefecture: '北海道'}, {id: 2, prefecture: '青森県'}, {id: 3, prefecture: '岩手県'},
                {id: 4, prefecture: '宮城県'}, {id: 5, prefecture: '秋田県'}, {id: 6, prefecture: '山形県'},
                {id: 7, prefecture: '福島県'}, {id: 8, prefecture: '茨城県'}, {id: 9, prefecture: '栃木県'},
                {id: 10, prefecture: '群馬県'}, {id: 11, prefecture: '埼玉県'}, {id: 12, prefecture: '千葉県'},
                {id: 13, prefecture: '東京都'}, {id: 14, prefecture: '神奈川県'}, {id: 15, prefecture: '新潟県'},
                {id: 16, prefecture: '富山県'}, {id: 17, prefecture: '石川県'}, {id: 18, prefecture: '福井県'},
                {id: 19, prefecture: '山梨県'}, {id: 20, prefecture: '長野県'}, {id: 21, prefecture: '岐阜県'},
                {id: 22, prefecture: '静岡県'}, {id: 23, prefecture: '愛知県'}, {id: 24, prefecture: '三重県'},
                {id: 25, prefecture: '滋賀県'}, {id: 26, prefecture: '京都府'}, {id: 27, prefecture: '大阪府'},
                {id: 28, prefecture: '兵庫県'}, {id: 29, prefecture: '奈良県'}, {id: 30, prefecture: '和歌山県'},
                {id: 31, prefecture: '鳥取県'}, {id: 32, prefecture: '島根県'}, {id: 33, prefecture: '岡山県'},
                {id: 34, prefecture: '広島県'}, {id: 35, prefecture: '山口県'}, {id: 36, prefecture: '徳島県'},
                {id: 37, prefecture: '香川県'}, {id: 38, prefecture: '愛媛県'}, {id: 39, prefecture: '高知県'},
                {id: 40, prefecture: '福岡県'}, {id: 41, prefecture: '佐賀県'}, {id: 42, prefecture: '長崎県'},
                {id: 43, prefecture: '熊本県'}, {id: 44, prefecture: '大分県'}, {id: 45, prefecture: '宮崎県'},
                {id: 46, prefecture: '鹿児島県'}, {id: 47, prefecture: '沖縄県'}, {id:48, prefecture: '未定'}

  ]

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
  has_many :categories, through: :size_categories
end

app/models/size_category.rb
class SizeCategory < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :size, optional: true
end

app/models/state.rb
class State < ActiveHash::Base
  self.data = [
                {id: 1, state: "新品､未使用"}, {id: 2, state: "未使用に近い"}, {id: 3, state: "目立った傷や汚れあり"}, 
                {id: 4, state: "やや傷や汚れあり"}, {id: 5, state: "傷や汚れあり"}, {id: 6, state: "全体的に状態が悪い"}
  ]
end

app/models/street.rb
class Street < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :items
         
         has_one :card
         has_one :profile
         has_one :street


         accepts_nested_attributes_for :street

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    # @items = Item.find(params[:id])

    @parents = Category.where(ancestry: nil).order("id ASC").limit(9)

  end

  def search
    @parents = Category.all.order("id ASC").limit(13)
    @items = Item.where('name LIKE(?)', "%#{params[:keyword]}%").order("created_at DESC").page(params[:page]).per(15)
    if params[:keyword] == ""
      redirect_to '/'
    end
    if @items.count == 0
      @all_items = Item.limit(25).order("created_at DESC")
    end
  end

  def edit
    @item = Item.find(21)
    @photo = @item.photos
  end

  def new
    @parents = Category.where(ancestry: nil)
    @category = Category.all.order("id ASC").limit(13)
    @postage = Postage.all.order("id ASC").limit(2)
    @prefecture = Prefecture.all
    @postage_day = PostageDay.all
    @state = State.all
    @item = Item.new
    @item.photos.build
  end

  def category_children
    @category_children = Category.find(params[:productcategory]).children
  end


  def category_grandchildren
    @category_grandchildren = Category.find(params[:productcategory]).children
    end

  def postage_children
    @postage_children = Postage.find(params[:postageitem]).children
  end


  def create
    @item = Item.new(item_params)
    @parents = Category.where(ancestry: nil)
    if @item.save
    redirect_to root_path
    else redirect_to new_item_path
    end
  end




  def show
    @items = Item.find(params[:id])
  end

  def goods_detail
    @items = Item.find(params[:id])
  end

  def destroy
    item = Item.find(params[:id])
    if item.user_id == current_user.id
      item.destroy
      redirect_to :controller => "users", :action => "goods", :id => current_user.id
    end
  end

  


  private

  def user_search_params
    params.fetch(:search, {}).permit(:id,:prefecture)
  end

  def item_params
    params.require(:item).permit(:state_id, :name, :explain, :category_id, :price, :buyer_id, :postage_id, :prefecture_id, :postage_day_id, photos_attributes: [:id, :img]).merge(user_id: current_user.id, shipping_date: 1, size_id: 1, brand_id: 1)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/payjp_helper.rb
module PayjpHelper
  def embedded_svg filename, options={}
    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
end

class MyPayjp
  Payjp::api_key = ENV['PAYJP_PRIVATE_KEY']
end
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.haml
.product_listing_content
  = render "user-shared/user-header"
  .product_listing_box
    .product_listing_title
      商品の情報を入力
    = form_with(model: @item, local: true, multipart: true, id: "form") do |f|
      .upload_box
        .upload_text
          .upload_header
            出品画像
          .upload_require
            必須
        %p
          最大6枚までアップロードできます
          %br [選択ボタンをクリックしてください]
        .photo_form
          = f.fields_for @photo do |i|
            .img_box_boxs
              .img_box1
              .img_box2
              .img_box3
              .img_box4
              .img_box5
              .img_box6
            .photo_form_box
              .photo_display1
                = i.label :img, class: "image_label1", for: "image", id: "photo"  do
                  = i.file_field :img, name: "item[photos_attributes][0][img]", multipart: true, class: "file_field1", id: "image", style: "color: red"
                  選択
                .remove_btn1
                  削除
              .photo_display2
                = i.label  :img, class: "image_label2", for: "image2", id: "photo2" do
                  = i.file_field :img, name: "item[photos_attributes][1][img]", multipart: true, class: "file_field2", id: "image2", style: "color: brown"
                  選択
                .remove_btn2
                  削除
              .photo_display3
                = i.label :img, class: "image_label3", for: "image3", id: "photo3" do
                  = i.file_field :img, name: "item[photos_attributes][2][img]", multipart: true, class: "file_field3", id: "image3", style: "color: blueviolet"
                  選択
                .remove_btn3
                  削除
              .photo_display4
                = i.label :img, class: "image_label4", for: "image4", id: "photo4" do
                  = i.file_field :img, name: "item[photos_attributes][3][img]", multipart: true, class: "file_field4", id: "image4", style: "color: rgb(226, 43, 144)"
                  選択
                .remove_btn4
                  削除
              .photo_display5
                = i.label :img, class: "image_label5", for: "image5", id: "photo5" do
                  = i.file_field :img, name: "item[photos_attributes][4][img]", multipart: true, class: "file_field5", id: "image5", style: "color: rgb(86, 226, 43)"
                  選択
                .remove_btn5
                  削除
              .photo_display6
                = i.label :img, class: "image_label6", for: "image6", id: "photo6" do
                  = i.file_field :img, name: "item[photos_attributes][5][img]", multipart: true, class: "file_field6", id: "image6", style: "color: rgb(43, 183, 226)"
                  選択
                .remove_btn6
                  削除
      

      .product_content
        .product_box-description
          .product_header
            商品名
          .product_require
            必須  
        = f.text_field :name, placeholder: "商品名（必須 40文字まで)", class: "product_description"
        .product_box-explain
          .product_header
            商品の説明
          .product_require
            必須
        = f.text_area :explain, placeholder: "商品の説明 (必須 1000文字以内) (色、素材、重さ、定価、注意点など) 例) 2010年頃に1万円で購入したジャケットです。ライトグレーではありません。あわせやすいのでおすすめです。", class: "product_explain"

      .product_content2
        .product_box-details
          商品の詳細
        .product_select-details
          .product_select-group
            .product_header
              カテゴリー
            .product_require
              必須
          .product_category-select
            -# = f.collection_select :category_id, @category, :id, :category_name, { prompt: "---" }, { class: "category_select-box", id: "category_select" }
            %i.fa.fa-chevron-down
          .product_select-children
          .product_select-group2
            .product_header
              商品の状態
            .product_require
              必須
          .product_state-select
            -# = f.collection_select :state_id, @state, :id, :state, { prompt: "---" }, { class: "state_select-box" }
            %i.fa.fa-chevron-down
          
      .product_content3
        .product_box-postage
          配送について
          = link_to " ", class: "question" do
            ?
        .product_select-postage    
          .product_postage-group
            .product_header
              送料の負担
            .product_require
              必須 
          .product_postage-select
            -# = f.collection_select :postage_id, @postage, :id, :postage, { prompt: "---" }, { class: "postage_select-box", id: "postage_select" }
            %i.fa.fa-chevron-down
          .product_select-postage_children
          .product_postage-group2
            .product_header
              発送元の地域
            .product_require
              必須
          .product_region-select
            -# = f.collection_select :prefecture_id, @prefecture, :id, :prefecture, {prompt: "---"}, {class: "region_select-box", id: "region_select"}
            %i.fa.fa-chevron-down
          .product_select-group3
            .product_header
              発送までの日数
            .product_require
              必須
          .product_days-select
            -# = f.collection_select :postage_day_id, @postage_day, :id, :postage_day, {prompt: "---"}, {class: "days_select-box", id: "days_select"}
            %i.fa.fa-chevron-down

      .product_content4
        .product_box-price
          販売価格(300〜9,999,999)
          = link_to " ", class: "question" do
            ?
        .product_price
          .product_price-group
            .product_header
              価格
            .product_require
              必須 
          .product_price-form
            ¥
            %input#price_calc.price_form-box{placeholder: "例) 300", type: "number"}/
          .product_price-fee
            販売手数料(10%)
            .right_bar
            
          .product_profit
            販売利益
            = f.number_field :price, style: "display: none", id: "price"
            .right_bar_2
              

      .product_content5
        .product_notice
          = link_to " " do
            禁止されている出品
          ,
          = link_to " " do
            行為
          を必ずご確認ください｡
          %br
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            =link_to " " do
              偽ブランドの販売
            は犯罪であり処罰される可能性があります｡
          また、出品をもちまして
          = link_to "/items/:id/edit/ " do
            加盟店規約
          に同意したことになります｡
        .product_exhibit-box
          = f.submit "出品する", class: "submit"
        .product_back-box
          =link_to root_path do
            戻る




  = render "user-shared/user-fotter" 

app/views/items/goods_detail.html.haml
.wrapper
  = render 'shared/header'
  - breadcrumb :goods_detail
  = render 'shared/breadcrumbs'

  .detail-main-box
    .action-choice-content
      = link_to '商品の編集', edit_item_path(@items), class: "action-edit-c"
      %p.text-or
        or
      .destroy-content
        = link_to 'この商品を削除する', item_path(@items.id), method: :delete, class: "choice-destroy", data: {confirm: "本当に削除しますか？"}


  = render 'shared/footer'
  = render 'shared/exhibition-btn'

app/views/items/index.haml
.wrapper
  = render 'shared/header'
  = render 'shared/slick-banner'
  = render 'shared/all-contents'
  = render 'shared/under-banner'
  = render 'shared/footer'
  = render 'shared/exhibition-btn'

app/views/items/items_show.haml
= render 'shared/header'
= render 'shared/product-details'
= render 'shared/under-banner'
= render 'shared/footer'

app/views/items/new.html.haml
.product_listing_content
  = render "user-shared/user-header" 
  .product_listing_box
    .product_listing_title
      商品の情報を入力
    = form_with(model: @item, local: true, multipart: true) do |f|
      .upload_box
        .upload_text
          .upload_header 
            出品画像
          .upload_require 
            必須
        %p
          最大6枚までアップロードできます
          %br [選択ボタンをクリックしてください]
        .photo_form
          = f.fields_for :photos do |i|
            .img_box_boxs
              .img_box1
              .img_box2
              .img_box3
              .img_box4
              .img_box5
              .img_box6
            .photo_form_box
              .photo_display1
                = i.label :img, class: "image_label1", for: "image", id: "photo"  do
                  = i.file_field :img, name: "item[photos_attributes][0][img]", multipart: true, class: "file_field1", id: "image", style: "color: red"
                  選択
                .remove_btn1
                  削除
              .photo_display2
                = i.label  :img, class: "image_label2", for: "image2", id: "photo2" do
                  = i.file_field :img, name: "item[photos_attributes][1][img]", multipart: true, class: "file_field2", id: "image2", style: "color: brown"
                  選択
                .remove_btn2
                  削除
              .photo_display3
                = i.label :img, class: "image_label3", for: "image3", id: "photo3" do
                  = i.file_field :img, name: "item[photos_attributes][2][img]", multipart: true, class: "file_field3", id: "image3", style: "color: blueviolet"
                  選択
                .remove_btn3
                  削除
              .photo_display4
                = i.label :img, class: "image_label4", for: "image4", id: "photo4" do
                  = i.file_field :img, name: "item[photos_attributes][3][img]", multipart: true, class: "file_field4", id: "image4", style: "color: rgb(226, 43, 144)"
                  選択
                .remove_btn4
                  削除
              .photo_display5
                = i.label :img, class: "image_label5", for: "image5", id: "photo5" do
                  = i.file_field :img, name: "item[photos_attributes][4][img]", multipart: true, class: "file_field5", id: "image5", style: "color: rgb(86, 226, 43)"
                  選択
                .remove_btn5
                  削除
              .photo_display6
                = i.label :img, class: "image_label6", for: "image6", id: "photo6" do
                  = i.file_field :img, name: "item[photos_attributes][5][img]", multipart: true, class: "file_field6", id: "image6", style: "color: rgb(43, 183, 226)"
                  選択
                .remove_btn6
                  削除
      

      .product_content
        .product_box-description
          .product_header
            商品名
          .product_require
            必須  
        = f.text_field :name, placeholder: "商品名（必須 40文字まで)", class: "product_description"
        .product_box-explain
          .product_header
            商品の説明
          .product_require
            必須
        = f.text_area :explain, placeholder: "商品の説明 (必須 1000文字以内) (色、素材、重さ、定価、注意点など) 例) 2010年頃に1万円で購入したジャケットです。ライトグレーではありません。あわせやすいのでおすすめです。", class: "product_explain"

      .product_content2
        .product_box-details
          商品の詳細
        .product_select-details
          .product_select-group
            .product_header
              カテゴリー
            .product_require
              必須
          .product_category-select
            = f.collection_select :category_id, @category, :id, :category_name, { prompt: "---" }, { class: "category_select-box", id: "category_select" }
            %i.fa.fa-chevron-down
          .product_select-children
          .product_select-group2
            .product_header
              商品の状態
            .product_require
              必須
          .product_state-select
            = f.collection_select :state_id, @state, :id, :state, { prompt: "---" }, { class: "state_select-box" }
            %i.fa.fa-chevron-down
          
      .product_content3
        .product_box-postage
          配送について
          = link_to " ", class: "question" do
            ?
        .product_select-postage    
          .product_postage-group
            .product_header
              送料の負担
            .product_require
              必須 
          .product_postage-select
            = f.collection_select :postage_id, @postage, :id, :postage, { prompt: "---" }, { class: "postage_select-box", id: "postage_select" }
            %i.fa.fa-chevron-down
          .product_select-postage_children
          .product_postage-group2
            .product_header
              発送元の地域
            .product_require
              必須
          .product_region-select
            = f.collection_select :prefecture_id, @prefecture, :id, :prefecture, {prompt: "---"}, {class: "region_select-box", id: "region_select"}
            %i.fa.fa-chevron-down
          .product_select-group3
            .product_header
              発送までの日数
            .product_require
              必須
          .product_days-select
            = f.collection_select :postage_day_id, @postage_day, :id, :postage_day, {prompt: "---"}, {class: "days_select-box", id: "days_select"}
            %i.fa.fa-chevron-down

      .product_content4
        .product_box-price
          販売価格(300〜9,999,999)
          = link_to " ", class: "question" do
            ?
        .product_price
          .product_price-group
            .product_header
              価格
            .product_require
              必須 
          .product_price-form
            ¥
            %input#price_calc.price_form-box{placeholder: "例) 300", type: "number"}/
          .product_price-fee
            販売手数料(10%)
            .right_bar
            
          .product_profit
            販売利益
            = f.number_field :price, style: "display: none", id: "price"
            .right_bar_2
              

      .product_content5
        .product_notice
          = link_to " " do
            禁止されている出品
          ,
          = link_to " " do
            行為
          を必ずご確認ください｡
          %br
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            =link_to " " do
              偽ブランドの販売
            は犯罪であり処罰される可能性があります｡
          また、出品をもちまして
          = link_to "/items/:id/edit/ " do
            加盟店規約
          に同意したことになります｡
        .product_exhibit-box
          = f.submit "出品する", class: "submit"
        .product_back-box
          =link_to root_path do
            戻る




  = render "user-shared/user-fotter" 

app/views/items/search.html.haml
.big-box
  = render 'shared/header'
  .main-box-big
    .left-big-content
      .details
        = form_with class: "details-form" do |f|
          %select.search-shuffle(name="shuffle")
            %option(value="並び替え")並び替え
            %option(value="価格の安い順")価格の安い順
            %option(value="かかくの高い順")価格の高い順
            %option(value="出品の安い順")出品の古い順
            %option(value="出品の高い順")出品の新しい順
            %option(value="いいねの多い順")いいねの多い順


          .search-refine
            %h3詳細検索

            .form-sort
              %lavel
                %i
                  %span.tbキーワードを追加
              %input(type="text" class="area-form")

            .form-sort
              %lavel
                %i
                  %span.tbカテゴリーを選択する
              = f.collection_select :select_category, @parents, :id, :category_name

            .form-sort
              %lavel
                %i
                  %span.tbブランド名から探す
              %input(type="text" placeholder="例)シャネル" class="area-form")

            .form-sort
              %lavel
                %i
                  %span.tbサイズを指定する
              = f.collection_select :select_size, @parents, :id, :category_name #仮後で変更する

            .form-sort
              %lavel
                %i
                  %span.tb価格
              = f.collection_select :select_size, @parents, :id, :category_name #仮後で変更する
              %input(type="text")
              %span &sim;
              %input(type="text")

            .form-sort
              %lavel
                %i
                  %span.tb商品の状態


            .form-sort
              %lavel
                %i
                  %span.tb配送料の負担


            .form-sort
              %lavel
                %i
                  %span.tb販売状況


            .form-sort-btn
              .form-sort-reset
              = f.submit '完了', class: 'form-sort-clear'

    .right-big-content
      .result
        %h2〇〇
        %spanの検索結果
      .result-number
        1-〇〇件表示

      .result-box
        - if @items.count == 0
          - @all_items.each do |item|
            %section.item-result
              = link_to item_path(item) do
                .item-photo-box
                  = image_tag item.photos[0].img.url, size: '160x160'
                  - if item.buyer_id.present?
                    .items-box_photo__sold
                      .items-box_photo__sold__inner
                        SOLD
                .item-body-box
                  %h3
                    = item.name
                  .item-body-box-val
                    .item-price
                      ￥
                      = item.price
        - else
          - @items.each do |item|
            %section.item-result
              = link_to item_path(item) do
                .item-photo-box
                  = image_tag item.photos[0].img.url, size: '160x160'
                  - if item.buyer_id.present?
                    .items-box_photo__sold
                      .items-box_photo__sold__inner
                        SOLD
                .item-body-box
                  %h3
                    = item.name
                  .item-body-box-val
                    .item-price
                      ￥
                      = item.price

  = render 'shared/footer'
  = render 'shared/exhibition-btn'

app/views/items/show.haml
= render 'shared/header'

= render 'shared/product-details'
= render 'shared/under-banner'
= render 'shared/footer'