config/routes.rb
Rails.application.routes.draw do

  root to: "items#index"
  devise_for :users

  resources :items do
    collection do
      get 'category_children'
      get 'category_grandchildren'
      get 'postage_children'
      get 'item_confilm'
      get 'search'
    end

    member do
      get 'goods_detail'
    end
  end


  resources :users do
    member do
      get 'goods'
      get 'purchase'
    end
  end


  resources :ragistrations do
    collection do
      get 'member'
      get 'authentication'
      get 'address'
      get 'complete'
      get 'userlogout'
      get 'payment'
    end
  end


  resources :cards, only: [:create, :show, :new, :index] do
    collection do
      post 'pay'
      post 'delete', to: 'cards#delete'
      post 'show'
      get 'confirmation'
      get 'mypay'
   

    end
  end


  resources :purchase, only: [:index] do
    member do
      get 'item_confilm', to: 'purchase#item_confilm'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items 
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :user, optional: true
 
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :items
  has_many :sizes, through: :size_categories
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :postage_day
  belongs_to_active_hash :state
  belongs_to :postage

  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  belongs_to :buyer,class_name:"User", optional: true
  belongs_to :user,class_name:"User", optional: true
  belongs_to :size, optional: true
  belongs_to :category, optional: true
  belongs_to :brand, optional: true


end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :item, optional: true
  mount_uploader :img, PhotoUploader
  

end

app/models/postage.rb
class Postage < ApplicationRecord
  has_ancestry
  has_many :items
end

app/models/postage_day.rb
class PostageDay < ActiveHash::Base
  self.data = [ 
                {id: 1, postage_day: '1~2日で発送'},
                {id: 2, postage_day: '2~3日で発送'},
                {id: 3, postage_day: '4~7日で発送'}
  ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
                {id: 1, prefecture: '北海道'}, {id: 2, prefecture: '青森県'}, {id: 3, prefecture: '岩手県'},
                {id: 4, prefecture: '宮城県'}, {id: 5, prefecture: '秋田県'}, {id: 6, prefecture: '山形県'},
                {id: 7, prefecture: '福島県'}, {id: 8, prefecture: '茨城県'}, {id: 9, prefecture: '栃木県'},
                {id: 10, prefecture: '群馬県'}, {id: 11, prefecture: '埼玉県'}, {id: 12, prefecture: '千葉県'},
                {id: 13, prefecture: '東京都'}, {id: 14, prefecture: '神奈川県'}, {id: 15, prefecture: '新潟県'},
                {id: 16, prefecture: '富山県'}, {id: 17, prefecture: '石川県'}, {id: 18, prefecture: '福井県'},
                {id: 19, prefecture: '山梨県'}, {id: 20, prefecture: '長野県'}, {id: 21, prefecture: '岐阜県'},
                {id: 22, prefecture: '静岡県'}, {id: 23, prefecture: '愛知県'}, {id: 24, prefecture: '三重県'},
                {id: 25, prefecture: '滋賀県'}, {id: 26, prefecture: '京都府'}, {id: 27, prefecture: '大阪府'},
                {id: 28, prefecture: '兵庫県'}, {id: 29, prefecture: '奈良県'}, {id: 30, prefecture: '和歌山県'},
                {id: 31, prefecture: '鳥取県'}, {id: 32, prefecture: '島根県'}, {id: 33, prefecture: '岡山県'},
                {id: 34, prefecture: '広島県'}, {id: 35, prefecture: '山口県'}, {id: 36, prefecture: '徳島県'},
                {id: 37, prefecture: '香川県'}, {id: 38, prefecture: '愛媛県'}, {id: 39, prefecture: '高知県'},
                {id: 40, prefecture: '福岡県'}, {id: 41, prefecture: '佐賀県'}, {id: 42, prefecture: '長崎県'},
                {id: 43, prefecture: '熊本県'}, {id: 44, prefecture: '大分県'}, {id: 45, prefecture: '宮崎県'},
                {id: 46, prefecture: '鹿児島県'}, {id: 47, prefecture: '沖縄県'}, {id:48, prefecture: '未定'}

  ]

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
  has_many :categories, through: :size_categories
end

app/models/size_category.rb
class SizeCategory < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :size, optional: true
end

app/models/state.rb
class State < ActiveHash::Base
  self.data = [
                {id: 1, state: "新品､未使用"}, {id: 2, state: "未使用に近い"}, {id: 3, state: "目立った傷や汚れあり"}, 
                {id: 4, state: "やや傷や汚れあり"}, {id: 5, state: "傷や汚れあり"}, {id: 6, state: "全体的に状態が悪い"}
  ]
end

app/models/street.rb
class Street < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :items
         
         has_one :card
         has_one :profile
         has_one :street


         accepts_nested_attributes_for :street

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

    require "payjp"

    def new
      card = Card.where(user_id: current_user.id)
      if card.exists?
        redirect_to delete_cards_path
      else
        @card = Card.new
      end
    end


    def pay
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      if params['payjp-token'].blank?
        redirect_to action: "new"

      else
        customer = Payjp::Customer.create(
          card: params['payjp-token'],
          # metadata: {user_id: current_user.id}
        )
        @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
        if @card.save
          redirect_to root_path
        else
          redirect_to action: "pay"
        end
      end
    end


    def delete 
      card = Card.where(user_id: current_user.id).first
      if card.blank?
      else
        Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
        customer = Payjp::Customer.retrieve(card.customer_id)
        customer.delete
        card.delete
      end
        redirect_to action: "new"
    end

    def show
        Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]

        card = Card.where(user_session).first
        if card.present?
        customer = Payjp::Customer.retrieve(card.customer_id)
        @default_card_information = customer.cards.retrieve(card.card_id)


        @card_brand = @default_card_information.brand
        case @card_brand
        when "Visa"
          @card_src = "visa.png"
        when "JCB"
          @card_src = "jcb.jpeg"
        when "MasterCard"
          @card_src = "master-card.png"
        when "American Express"
          @card_src = "american_express.png"
        when "Diners Club"
          @card_src = "dinersclub.png"
        when "Discover"
          @card_src = "discover.jpeg"
        end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/payjp_helper.rb
module PayjpHelper
  def embedded_svg filename, options={}
    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
end

class MyPayjp
  Payjp::api_key = ENV['PAYJP_PRIVATE_KEY']
end
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/confirmation.html.haml
.main__content
  %section.chapter__container
    %h2.chapter__head 支払い方法
    .payment__main
      .payment__list
        .payment__list__content
          %h3.sub__head クレジットカード一覧
      .add__card
        .payment__list__content
          = link_to new_card_path(current_user), class: "red__btn", data: {"turbolinks" => false} do
            %i
            = fa_icon('credit-card', class: "card__icon")
            クレジットカードを追加する
      .not__regist
        %span 支払い方法について
        

app/views/cards/mypay.haml
= render "shared/header"
- breadcrumb :paypay
= render "shared/breadcrumbs"
.main__content
  = render "shared/side-bar"
  %section.chapter__container
    %h2.chapter__head 支払い方法
    .payment__main
      .payment__list
        .payment__list__content
          %h3.sub__head 
            クレジットカード一覧
      .add__card
        .payment__list__content
          = link_to new_card_path(current_user), class: "red__btn", data: {"turbolinks" => false} do
            %i
            = fa_icon('credit-card', class: "card__icon")
            クレジットカードを追加する
      .not__regist
        %span 支払い方法について
= render 'shared/footer'
= render 'shared/exhibition-btn'

app/views/cards/new.haml
.wrapper
  = render 'shared/header'
  - breadcrumb :add_card
  = render 'shared/breadcrumbs'
  .main__content
    = render 'shared/side-bar'
    %section.chapter__cont
      %h2.chapter__head クレジットカード情報入力
      = form_with url: pay_cards_path, method: :post,   html: {name: "inputForm"} do |f|
        .form__main__container
          .form__content
            %label.payment__card
              カード番号
              %span.require__form
                必須
            = f.text_field :number, class: "number-deafult", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            .card__list
              .card__list__picture
          .form__content.top__margin
            %label.payment__card
              有効期限
              %span.require__form
                必須
            .select__box.top__margin
              .select__box__half
                = f.select :exp_month,[["--",""],["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'select__default'
                %span 月
              .select__box__half
                .icon
                = f.select :exp_year,[["--",""],["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'select__default'
                %span  年
          .form__content.top__margin
            %label.payment__card
              セキュリティーコード
              %span.require__form
                必須
            = f.text_field :cvc, class: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
            .single__code
              %span.form__question ?
              %span カードの裏面の番号とは？
          #card_token
          = f.submit "追加する",id: "token_submit", class: "pay-new-move-text"
  = render 'shared/footer'
  = render 'shared/exhibition-btn'

:javascript
  document.addEventListener(
  "DOMContentLoaded", e => {
    if (document.getElementById("token_submit") != null) { 
      Payjp.setPublicKey("pk_test_57f5b7abfc1b1cbd41160d6a"); 
      let btn = document.getElementById("token_submit"); 
      btn.addEventListener("click", e => { 
        e.preventDefault(); 
        let card = {
          number: document.getElementById("card_number").value,
          cvc: document.getElementById("cvc").value,
          exp_month: document.getElementById("exp_month").value,
          exp_year: document.getElementById("exp_year").value
        }; 
        Payjp.createToken(card, (status, response) => {
          if (status === 200) { 
            $("#card_number").removeAttr("name");
            $("#cvc").removeAttr("name");
            $("#exp_month").removeAttr("name");
            $("#exp_year").removeAttr("name"); 
            $("#card_token").append(
              $('<input type="hidden" name="payjp-token">').val(response.id)
            ); 
            document.inputForm.submit();
            alert("登録が完了しました"); 
          } else {
            alert("カード情報が正しくありません。"); 
          }
        });
      });
    }
  },
  false
  );

app/views/cards/pay.haml
= render "shared/header"
= render "shared/breadcrumbs"
.main__content
  = render "shared/side-bar"
  %section.chapter__container
    %h2.chapter__head 支払い方法
    .payment__main
      .payment__list
        .payment__list__content
          %h3.sub__head 
            クレジットカード一覧
      .add__card
        .payment__list__content
          = link_to new_card_path(current_user), class: "red__btn", data: {"turbolinks" => false} do
            %i
            = fa_icon('credit-card', class: "card__icon")
            クレジットカードを追加する
      .not__regist
        %span 支払い方法について
= render 'shared/footer'
= render 'shared/exhibition-btn'   

     

app/views/cards/paypay.haml
.main__content
  %section.chapter__container
    %h2.chapter__head クレジットカード情報入力
    = form_tag( pay_cards_path, method: :post, action: "create", id: 'charge-form',  name: "inputForm", class: "chapter__container__inner") do
      .form__main__container
        .form__content
          %label.payment__card カード番号
          %span.require__form 必須
          = text_field_tag "number", "", class: "number input__deafult", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          .card__list
            .card__list__picture
        .form__content.top__margin
          %label.payment__card 有効期限
          %span.require__form 必須
          .select__box.top__margin
            .select__box__half
              %select.select__default#exp_month{name: "exp_month", type: "text"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %i
                -# = icon('fas', 'chevron-down')
              %span 月
            .select__box__half
              .icon
              %select.select__default#exp_year{name: "exp_year", type: "text"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %i
                -# = icon('fas', 'chevron-down')
              %span  年
        .form__content.top__margin
          %label セキュリティーコード
          %span.require__form 必須
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
          .single__code
            .single__code__text
            %span.form__question ? 
            %span カードの裏面の番号とは？
        #card_token
        = submit_tag "追加する", id: "token_submit", class: "top__margin"

:javascript
  document.addEventListener(
  "DOMContentLoaded", e => {
    if (document.getElementById("token_submit") != null) { 
      Payjp.setPublicKey("pk_test_57f5b7abfc1b1cbd41160d6a"); 
      let btn = document.getElementById("token_submit"); 
      btn.addEventListener("click", e => { 
        e.preventDefault(); 
        let card = {
          number: document.getElementById("card_number").value,
          cvc: document.getElementById("cvc").value,
          exp_month: document.getElementById("exp_month").value,
          exp_year: document.getElementById("exp_year").value
        }; 
        Payjp.createToken(card, (status, response) => {
          if (status === 200) { 
            $("#card_number").removeAttr("name");
            $("#cvc").removeAttr("name");
            $("#exp_month").removeAttr("name");
            $("#exp_year").removeAttr("name"); 
            $("#card_token").append(
              $('<input type="hidden" name="payjp-token">').val(response.id)
            ); 
            document.inputForm.submit();
            alert("登録が完了しました"); 
          } else {
            alert("カード情報が正しくありません。"); 
          }
        });
      });
    }
  },
  false
  );

app/views/cards/show.haml
= render "shared/header"
- breadcrumb :create_card
= render "shared/breadcrumbs"
.main__content
  = render "shared/side-bar"
  %section.chapter__container
    %h2.chapter__head 支払い方法
    .payment__main
      .payment__list
        .payment__list__content
          %h3.sub__head クレジットカード一覧
      .card__payment__list
        .card__box
          %form.card__payment__content
          .card__list
            .card__list__picture  
              = image_tag "cards/#{@card_src}", width: '26', height: '20', alt: @card_brand, id: "card_image"
          .card__number 
            = "**** **** **** " + @default_card_information.last4
          .expire__date 
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          = form_tag( delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
            %input{ type: "hidden", name: "card_id", value: "" }
            %button.delete__button 削除する
        .how__not__regist
          %span 支払い方法について
= render 'shared/footer'
= render 'shared/exhibition-btn'